Add support for sections in the doc
reconquest/shdoc pull request #54
Opened 2022-08-22 15:00 UTC by Ariana-Hlavaty-i2

Feature request implementation. Resolves #53

2022-08-23 06:14 UTC, kovetskiy requested changes
Hi!

Thank you for your contribution.

A few nitpicks and we can merge the PR.

2022-08-23 06:14 UTC, kovetskiy commented on shdoc
> +      lines[0]=render("h2", section)
Could you add some spaces around `=` here?

2022-08-23 21:12 UTC, Ariana-Hlavaty-i2 reviewed
Required spaces added as per comments

2022-08-24 05:08 UTC, merged

2022-08-24 05:08 UTC, kovetskiy commented
Thanks!